var namespaces_dup =
[
    [ "add_command", "namespaceadd__command.html", "namespaceadd__command" ],
    [ "bezier_dialog", "namespacebezier__dialog.html", "namespacebezier__dialog" ],
    [ "boolean_item", "namespaceboolean__item.html", "namespaceboolean__item" ],
    [ "boolean_operations", "namespaceboolean__operations.html", "namespaceboolean__operations" ],
    [ "boundary_conditions_dialog", "namespaceboundary__conditions__dialog.html", "namespaceboundary__conditions__dialog" ],
    [ "command", "namespacecommand.html", "namespacecommand" ],
    [ "command_service", "namespacecommand__service.html", "namespacecommand__service" ],
    [ "comsol", "namespacecomsol.html", "namespacecomsol" ],
    [ "data_parser", "namespacedata__parser.html", "namespacedata__parser" ],
    [ "delete_command", "namespacedelete__command.html", "namespacedelete__command" ],
    [ "dialog", "namespacedialog.html", "namespacedialog" ],
    [ "dialog_factory", "namespacedialog__factory.html", "namespacedialog__factory" ],
    [ "doxytest", "namespacedoxytest.html", "namespacedoxytest" ],
    [ "drawing_service", "namespacedrawing__service.html", "namespacedrawing__service" ],
    [ "edge_item", "namespaceedge__item.html", "namespaceedge__item" ],
    [ "editable_bezier", "namespaceeditable__bezier.html", "namespaceeditable__bezier" ],
    [ "ellipse_dialog", "namespaceellipse__dialog.html", "namespaceellipse__dialog" ],
    [ "ellipse_item", "namespaceellipse__item.html", "namespaceellipse__item" ],
    [ "event_handler", "namespaceevent__handler.html", "namespaceevent__handler" ],
    [ "gmsh_mesh_builder", "namespacegmsh__mesh__builder.html", "namespacegmsh__mesh__builder" ],
    [ "graphics_view", "namespacegraphics__view.html", "namespacegraphics__view" ],
    [ "grid_scene", "namespacegrid__scene.html", "namespacegrid__scene" ],
    [ "initial_conditions_dialog", "namespaceinitial__conditions__dialog.html", "namespaceinitial__conditions__dialog" ],
    [ "line_dialog", "namespaceline__dialog.html", "namespaceline__dialog" ],
    [ "line_item", "namespaceline__item.html", "namespaceline__item" ],
    [ "main", "namespacemain.html", [
      [ "app", "namespacemain.html#a5fa94f0581009434c7a63791944d6ff4", null ],
      [ "DEBUG", "namespacemain.html#ae8965e6c35c2308660f2da93704f5890", null ],
      [ "font", "namespacemain.html#a2c83ac42c788ee1cb0d418310a430e75", null ],
      [ "format", "namespacemain.html#a758a4b3c52742d78aa30e49d058acea4", null ],
      [ "level", "namespacemain.html#ad39dcd94f0ffc845ab416c0783c20d25", null ],
      [ "stream", "namespacemain.html#a149044769e4240e5e123bc578375588d", null ],
      [ "window", "namespacemain.html#ae1ea5d7d8ba9156ef06beef9bf8901a8", null ]
    ] ],
    [ "main_window", "namespacemain__window.html", "namespacemain__window" ],
    [ "material_dialog", "namespacematerial__dialog.html", "namespacematerial__dialog" ],
    [ "mesh_dialog", "namespacemesh__dialog.html", "namespacemesh__dialog" ],
    [ "move_command", "namespacemove__command.html", "namespacemove__command" ],
    [ "mpl_canvas", "namespacempl__canvas.html", "namespacempl__canvas" ],
    [ "parametric_curve_item", "namespaceparametric__curve__item.html", "namespaceparametric__curve__item" ],
    [ "parametric_dialog", "namespaceparametric__dialog.html", "namespaceparametric__dialog" ],
    [ "plotter", "namespaceplotter.html", "namespaceplotter" ],
    [ "rect_dialog", "namespacerect__dialog.html", "namespacerect__dialog" ],
    [ "rectangle_item", "namespacerectangle__item.html", "namespacerectangle__item" ],
    [ "rotate_command", "namespacerotate__command.html", "namespacerotate__command" ],
    [ "selection_service", "namespaceselection__service.html", "namespaceselection__service" ],
    [ "template", "namespacetemplate.html", "namespacetemplate" ],
    [ "transformation_operations", "namespacetransformation__operations.html", "namespacetransformation__operations" ],
    [ "turbulence_dialog", "namespaceturbulence__dialog.html", "namespaceturbulence__dialog" ],
    [ "turbulence_models", "namespaceturbulence__models.html", "namespaceturbulence__models" ]
];